apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-web
          image: your-frontend-image:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_API_URL
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: ENV
            - name: ANALYTICS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: ANALYTICS_TOKEN
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
