apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
data:
  cluster.name: logging-cluster
  http.port: "2020"
  http.server: "On"
  logs.region: ap-south-1
